
language: node_js

node_js:
  - node
  - 14
  - 12
  - 10
  - 8

jobs:
  include:
    - stage: coverage
      node_js: 8
      script:
        - npm run test:cov
        - cat ./coverage/lcov.info | coveralls

sudo: false
